# Generated by Django 5.1.7 on 2025-03-26 22:28

import django.db.models.deletion
import phonenumber_field.modelfields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('flowerist', 'Флорист'), ('courier', 'Курьер')], max_length=20, verbose_name='Должность')),
                ('slug', models.SlugField(max_length=225, unique=True, verbose_name='ID персонала')),
                ('name', models.CharField(max_length=20, verbose_name='Имя')),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None, verbose_name='Телефон')),
                ('on_vacation', models.BooleanField(default=False, verbose_name='В отпуске?')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='staff', to=settings.AUTH_USER_MODEL, verbose_name='Связанный юзер')),
            ],
            options={
                'unique_together': {('name', 'phone')},
            },
        ),
    ]
