# Generated by Django 5.1.7 on 2025-03-28 18:04

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Тип события')),
            ],
            options={
                'verbose_name': 'Событие',
                'verbose_name_plural': 'События',
            },
        ),
        migrations.CreateModel(
            name='PriceInterval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_price', models.PositiveIntegerField(default=0, unique=True, verbose_name='Минимальная цена')),
                ('max_price', models.PositiveIntegerField(default=1, unique=True, verbose_name='Максимальная цена')),
            ],
            options={
                'verbose_name': 'Ценовой интервал',
                'verbose_name_plural': 'Ценовые интервалы',
                'ordering': ['min_price'],
            },
        ),
        migrations.AlterModelOptions(
            name='staff',
            options={'ordering': ['role'], 'verbose_name': 'Персонал', 'verbose_name_plural': 'Персонал'},
        ),
        migrations.RemoveField(
            model_name='staff',
            name='user',
        ),
        migrations.AlterField(
            model_name='staff',
            name='name',
            field=models.CharField(max_length=50, verbose_name='ФИО'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='on_vacation',
            field=models.BooleanField(default=False, verbose_name='В отпуске'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, null=True, region=None, unique=True, verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='slug',
            field=models.SlugField(blank=True, max_length=225, null=True, unique=True, verbose_name='ID персонала'),
        ),
        migrations.CreateModel(
            name='Component',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('flower', 'Цветок'), ('accessory', 'Аксессуар')], max_length=20, verbose_name='Тип элемента')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Название')),
                ('price', models.DecimalField(decimal_places=2, default=1.0, max_digits=10, verbose_name='Стоимость (руб.)')),
                ('image', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Изображение')),
                ('note', models.CharField(blank=True, max_length=100, verbose_name='Примечания')),
                ('stock', models.PositiveIntegerField(default=0, verbose_name='Стоковое количество')),
            ],
            options={
                'verbose_name': 'Элемент',
                'verbose_name_plural': 'Элементы',
                'ordering': ['type'],
                'unique_together': {('name', 'price')},
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='ФИО')),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, unique=True, verbose_name='Телефон')),
            ],
            options={
                'verbose_name': 'Клиент',
                'verbose_name_plural': 'Клиенты',
                'unique_together': {('name', 'phone')},
            },
        ),
        migrations.CreateModel(
            name='Bouquet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Название')),
                ('base_price', models.DecimalField(decimal_places=2, default=1.0, max_digits=10, verbose_name='Стоимость оформления (руб.)')),
                ('image', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Изображение')),
                ('description', models.CharField(max_length=100, verbose_name='описание')),
                ('available', models.BooleanField(default=True, verbose_name='В наличии')),
                ('events', models.ManyToManyField(blank=True, related_name='bouquets', to='backend.event', verbose_name='События')),
                ('price_interval', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bouquets', to='backend.priceinterval', verbose_name='Ценовой интервал')),
            ],
            options={
                'verbose_name': 'Букет',
                'verbose_name_plural': 'Букеты',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.TextField(verbose_name='Адрес')),
                ('desired_date', models.DateTimeField(verbose_name='Дата')),
                ('desired_time', models.TimeField(verbose_name='Время')),
                ('flowerist_comment', models.CharField(blank=True, max_length=200, null=True, verbose_name='Комментарии флористу')),
                ('delivery_comment', models.CharField(blank=True, max_length=200, null=True, verbose_name='Комментарии курьеру')),
                ('total_cost', models.FloatField(default=0.0, verbose_name='Общая стоимость')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата создания заказа')),
                ('bouquet', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='backend.bouquet', verbose_name='Букет')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_orders', to='backend.customer', verbose_name='Клиент')),
                ('courier', models.ForeignKey(limit_choices_to={'role': 'courier'}, on_delete=django.db.models.deletion.CASCADE, related_name='courier_orders', to='backend.staff', verbose_name='Курьер')),
                ('flowerist', models.ForeignKey(limit_choices_to={'role': 'flowerist'}, on_delete=django.db.models.deletion.CASCADE, related_name='flowerist_orders', to='backend.staff', verbose_name='Флорист')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
            },
        ),
        migrations.CreateModel(
            name='BouquetComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Количество')),
                ('bouquet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='components', to='backend.bouquet')),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.component')),
            ],
            options={
                'verbose_name': 'Компонент букета',
                'verbose_name_plural': 'Компоненты букетов',
                'unique_together': {('bouquet', 'component')},
            },
        ),
    ]
