# Generated by Django 5.1.7 on 2025-03-30 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_consultation_customer_event_pricerange_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricerange',
            name='max_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Максимальная цена (может быть NULL для отсутствия ограничений)'),
        ),
        migrations.AlterField(
            model_name='pricerange',
            name='min_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Минимальная цена (может быть NULL для отсутствия ограничения)'),
        ),
        migrations.AlterField(
            model_name='pricerange',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name="Название диапазона (например, 'До 1 000 руб')"),
        ),
    ]
