# Generated by Django 5.1.7 on 2025-03-30 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_consultation_customer_event_pricerange_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bouquet',
            name='base_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Стоимость оформления (руб.)'),
        ),
    ]
