# Generated by Django 5.1.7 on 2025-03-30 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_consultation_alter_order_desired_time'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='customer',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='bouquet',
            name='image',
            field=models.ImageField(null=True, upload_to='', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='name',
            field=models.CharField(max_length=50, unique=True, verbose_name='ФИО'),
        ),
    ]
