# Generated by Django 5.1.7 on 2025-03-30 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_alter_order_options_remove_order_address_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PriceRange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Название диапазона (например, 'До 1 000 руб')", max_length=100)),
                ('min_price', models.DecimalField(blank=True, decimal_places=2, help_text='Минимальная цена (может быть NULL для отсутствия ограничения)', max_digits=10, null=True)),
                ('max_price', models.DecimalField(blank=True, decimal_places=2, help_text='Максимальная цена (может быть NULL для отсутствия ограничений)', max_digits=10, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='PriceInterval',
        ),
    ]
