# Generated by Django 5.1.7 on 2025-03-30 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_pricerange_delete_priceinterval'),
    ]

    operations = [
        migrations.AddField(
            model_name='bouquet',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Общая стоимость'),
        ),
    ]
